# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :servidorUbuntu do |servidorUbuntu|
    servidorUbuntu.vm.box = "bento/ubuntu-20.04"
    servidorUbuntu.vm.network :private_network, ip: "192.168.104.2"
	  servidorUbuntu.vm.provision "shell", path:"provisionamientoServidor.sh"
    servidorUbuntu.vm.hostname = "servidorUbuntu"
  end
end