# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :servidorUbuntu do |servidorUbuntu|
    servidorUbuntu.vm.box = "bento/ubuntu-18.04"
    servidorUbuntu.vm.network :private_network, ip: "192.168.120.2"
    servidorUbuntu.vm.hostname = "servidorUbuntu"
    #servidorUbuntu.vm.provision :ansible do |ansible|
    #	ansible.playbook = "playbook.yml"
    #end
  
  end

end
